name: Automação de E-mails Ensaios

on:
  schedule:
    # Roda todo dia às 09:00 UTC (06:00 em Brasília)
    - cron: '0 9 * * *'
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install pandas boto3

      - name: Executar Script
        env:
          # Credenciais AWS para o Boto3 acessar o DynamoDB
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          # Credenciais de E-mail
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }} # Senha de App do Google
        run: python main.py